services:
    _defaults:
        autowire: true
        autoconfigure: true

    cart.repository.adapter.default:
        class: App\Cart\Infrastructure\CartDoctrineRepositoryAdapter

    App\Cart\Domain\CartRepositoryInterface: '@cart.repository.adapter.default'

    App\Cart\Domain\CartApplicationService:
        arguments:
            $repository: '@cart.repository.adapter.default'

