nelmio_api_doc:
    documentation:
        info:
            title: Siroko API
            description: Siroko API documentation
            version: 1.0.0
        servers:
            - url: http://localhost:8009
              description: Development server
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)