services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    entrypoint: ["php", "-S", "0.0.0.0:8000", "-t", "public/"]
    ports:
      - "8009:8000"
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASS}
        - MYSQL_ALLOW_EMPTY_PASSWORD=0
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_ROOT_HOST=%
    command: mysqld
    volumes:
        - mysql_vol:/var/lib/mysql
        - ./docker/mysql:/docker-entrypoint-initdb.d/
    ports:
      - "3309:3306"

volumes:
  mysql_vol:
