services:
    _defaults:
        autowire: true
        autoconfigure: true

    cart_line.repository.adapter.default:
        class: App\CartLine\Infrastructure\CartLineDoctrineRepositoryAdapter

    App\CartLine\Domain\CartLineRepositoryInterface: '@cart_line.repository.adapter.default'

    App\CartLine\Domain\CartLineApplicationService:
        arguments:
            $repository: '@cart_line.repository.adapter.default'

